# Jekyll configuration
name: Formularity
description: VIPER (Visual Inspection of Peak/Elution Relationships) can be used to visualize and characterize the features detected during LC-MS analyses.
url: https://pnnl-comp-mass-spec.github.io/Formularity/
